openapi: 3.0.0
info:
  title: 주식 거래 시스템 API
  description: |
    주식 거래 시스템의 API 명세서입니다.
    - 이 API는 매수, 매도 주문을 처리합니다.
    - 인증은 JWT 기반 Bearer Token을 사용합니다.
  version: 1.1.0

servers:
  - url: https://api.example.com/api # 추후 변경
    description: Production server
  - url: https://staging.example.com/api # 추후 변경
    description: Staging server
  - url: https://dev.example.com/api # 추후 변경
    description: Dev server

tags:
  - name: 주문
    description: 주식 주문 관련 API
  - name: 계좌
    description: 계좌 및 자금 관련 API
  - name: 사용자
    description: 사용자 계정 관리 API

# =================================================================
# 재사용 가능한 공통 컴포넌트 정의
# =================================================================
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  # -----------------------------------------------------
  # DTO(Data Transfer Object) 스키마
  # -----------------------------------------------------
  schemas:
    StockId:
      type: integer
      description: 주식의 시스템 내부 고유 ID
      example: 1
    OrderId:
      type: integer
      description: 주문의 고유 ID
      example: 12345
    OrderType:
      type: string
      description: 주문 유형
      enum:
        - BUY   # 매수
        - SELL  # 매도
      example: "BUY"
    StockDto:
      type: object
      properties:
        id:
          type: integer
          description: 주식 데이터 고유 ID
          example: 1
        ticker:
          type: string
          description: 종목 코드
          example: "AAPL"
        name:
          type: string
          description: 종목명
          example: "Apple Inc."
        currentPrice:
          type: number
          description: 현재가
          example: 150.75
        priceChange:
          type: number
          description: 전일 대비 가격 차이
          example: -1.25
        priceChangeRate:
          type: number
          description: 전일 대비 등락률 (%)
          example: -0.82
        lastUpdatedAt:
          type: string
          format: date-time
          description: 가격 갱신 시각
          example: "2025-07-31T06:30:00Z"
        totalVolumeToday:
          type: integer
          description: 오늘의 누적 거래량
          example: 50321400
    CreateOrderRequestV1:
      type: object
      required:
        - ticker
        - orderType
        - price
        - quantity
      properties:
        ticker:
          type: string
          description: 주문할 주식의 종목 코드
          example: "AAPL"
          minLength: 4
          maxLength: 4
        orderType: 
          $ref: '#/components/schemas/OrderType'
        price:
          type: number
          description: 1주당 주문 가격
          example: 150.00
          minimum: 1
        quantity:
          type: integer
          description: 주문 수량
          example: 10
          minimum: 1
    OrderResponseV1:
      type: object
      properties:
        orderId:
          type: integer
          example: 12345
        ticker:
          type: string
          example: "AAPL"
        orderType:
          $ref: '#/components/schemas/OrderType'
        price:
          type: number
          example: 150.00
        quantity:
          type: integer
          example: 10
        executedQuantity:
          type: integer
          description: 체결된 수량
          example: 0
        status:
          type: string
          enum: [PENDING, PARTIALLY_FILLED, COMPLETED, CANCELED]
          description: |
            주문 상태:
              - PENDING: 대기 중
              - PARTIALLY_FILLED: 일부 체결
              - COMPLETED: 완료
              - CANCELED: 취소됨
        createdAt:
          type: string
          format: date-time
          example: "2025-07-31T07:00:00Z"
        errorMessage:
          type: string
          example: "Insufficient balance"
    ErrorResponseDto:
      type: object
      description: API 요청 실패 시 공통 에러 응답
      properties:
        statusCode:
          type: integer
          example: 400
        message:
          type: string
          example: "Insufficient balance"
        error:
          type: string
          example: "Bad Request"

# =================================================================
# API 경로(Endpoint) 상세 정의
# =================================================================
paths:
/stocks:
    get:
      summary: 전체 주식 종목 목록 조회
      description: 거래 가능한 모든 주식 종목의 목록과 시세를 조회합니다.
      tags:
        - "시장 정보 API"
      responses:
        '200':
          description: 성공. 주식 목록 배열을 반환합니다. 종목이 없는 경우 빈 배열을 반환합니다.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StockDto'

/stocks/{ticker}:
    get:
      summary: 특정 주식 상세 정보 조회
      description: 특정 종목 코드(ticker)에 해당하는 주식의 상세 정보를 조회합니다.
      tags:
        - "시장 정보 API"
      parameters:
        - name: ticker
          in: path
          description: 조회할 주식의 종목 코드
          required: true
          schema:
            type: string
          example: "AAPL"
      responses:
        '200':
          description: 성공. 단일 주식 객체를 반환합니다.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockDto'
        '404':
          description: 리소스 없음 (e.g., 존재하지 않는 종목)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

/v1/orders:
    post:
      summary: 신규 주문 등록
      description: 사용자가 특정 주식에 대한 새로운 매수 또는 매도 주문을 등록합니다.
      tags:
        - 주문
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequestV1'
      responses:
        '201':
          description: 주문이 성공적으로 생성됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponseV1'
        '400':
          description: 잘못된 요청 (예: 잔고 부족)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '401':
          description: 인증 실패 (JWT 누락 또는 만료)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '404':
          description: 리소스 없음 (예: 존재하지 않는 종목)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

